language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
env:
  - DJANGO=1.10.*

script:
- python manage.py test
- flake8
notifications:
- email: false
- slack: rockstarz-team:3q5jXHqZrgq1rhqETX0OUcy9#build
